### ISSUE TITLE
[OPTION] Crop By Center

### ISSUE THREAD

**Issue by RibesAlexandre** [ayvazyan10/imagic#1]
Hi,

How is it possible to crop a picture by center ? I think it will be a great feature. 

Thanks

**Comment by ayvazyan10** [comment]
> Hi,
> 
> How is it possible to crop a picture by center ? I think it will be a great feature.
> 
> Thanks

By default x,y coordinates are optional to move the top-left corner of the cutout to a certain position.

if you pass 0, 0 it will do center cropping

`Imagic::make('Image')->resize(100, 100, 0, 0);`
