### ISSUE TITLE
Feature Request - Store to Filesystem DIsk

### ISSUE THREAD

**Issue by lorenzoaiello** [ayvazyan10/imagic#2]
This package is great, but would be even better with the ability to store the image to a Filesystem Disk similar to the native File Fields in Nova (https://nova.laravel.com/docs/4.0/resources/file-fields.html#customization).

**Comment by ayvazyan10** [comment]
Thank you for your feedback! I will take note of this feature request and consider it for future updates. While I cannot guarantee immediate implementation, I will prioritize it and aim to address it in the upcoming week or as soon as possible.

**Comment by Ruitjes** [comment]
@ayvazyan10 Can you also do `->disk("s3");` with this library to store all the images in S3 buckets. Package looks really promising!

**Comment by ayvazyan10** [comment]
All is added in v1.3.0

**Comment by imnpc** [comment]
> All is added in v1.3.0

only support local disk,can not use s3 or oss
